server:
  port: 8082
# 存储文件的路径
path:
  eTPSS:
    cmd: "/root/project4/c/eTPSS/build/eTPSS"
    #    data: "/root/project4/data/eTPSS/data.txt"
    #    res : "/root/project4/data/eTPSS/res.txt"
    data: "data/data.txt"
    res: "data/res.txt"
#path:
#  distributed:
#    drs:
#      cmd: ""
#      data: ""
#      res: ""
#    drsq:
#      cmd: ""
#      data: ""
#      res: ""
  notDistributed:
    range_search:
      data : "/root/project4/data/range_search/data.txt"
      queryFile : "/root/project4/data/range_search/query.txt"
      res : "/root/project4/data/range_search/res.txt"
    rsq:
      data: "/root/project4/data/rsq/data.txt"
      queryFile: "/root/project4/data/rsq/query.txt"
      res: "/root/project4/data/rsq/res.txt"
    skyline:
      data: "/root/project4/data/skyline/data.txt"
      queryFile: "/root/project4/data/skyline/query.txt"
      res: "/root/project4/data/skyline/res.txt"
    skq:
      data: "/root/project4/data/skq/data.txt"
      queryFile: "/root/project4/data/skq/query.txt"
      res: "/root/project4/data/skq/res.txt"
    ssq:
      data: "/root/project4/data/ssq/data.txt"
      queryFile: "/root/project4/data/ssq/query.txt"
      res: "/root/project4/data/ssq/res.txt"
port:
  address: "10.170.53.52"
  distributed:

  notDistributed:
    range_search: "9990"
    rsq: "9991"
    skyline: "9992"
    skq: "9993"
    ssq: "9994"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB
      file-size-threshold: 30MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
      username: "root"
      password: "011013"
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 600000
      timeBetweenEvictionRunsMillis: 60000
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
swagger:
  enabled: true
logging:
  level:
    root: INFO

cmd: "/root/project4/c/range_search/build/range_search"
