spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.xd.hufei.dto
  configuration:
    map-underscore-to-camel-case: true
server:
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: false
        same-site: none
        secure: true