server:
  port: 8082
# 存储文件的路径
path:
  eTPSS:
    cmd: ""
    data: ""
    res : ""
#path:
#  distributed:
#    drs:
#      cmd: ""
#      data: ""
#      res: ""
#    drsq:
#      cmd: ""
#      data: ""
#      res: ""
#  notDistributed:
#    range_search:
#      cmd: ""
#      data : ""
#      res : ""
#    rsq:
#      cmd: ""
#      data: ""
#      res: ""
#    skyline:
#      cmd: ""
#      data: ""
#      res: ""
#    skq:
#      cmd: ""
#      data: ""
#      res: ""
#    ssq:
#      cmd: ""
#      data: ""
#      res: ""
port:
  distributed:

  notDistributed:
    range_search:
      port: ""
      address: "localhost"

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 60MB
      file-size-threshold: 30MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://10.10.55.25:3306/heartmelody?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: T3stP@ssw0rd!
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000

swagger:
  enabled: true
logging:
  level:
    root: INFO
